name: Build and test
on:
  pull_request:
    branches: [ "develop", "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          
      - name: Install bundler
        run: bundle install
        
      - name: Run unit tests
        run: bundle exec fastlane runTests
        
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
